import type { ContinentKey } from "./ContinentMap";

const REGION_COUNTRIES: Record<ContinentKey, string[]> = {
  AMERYKA_PN: [
    "USA",
    "Canada",
    "Mexico",
    "Greenland",
    "Belize",
    "Costa Rica",
    "Cuba",
    "Dominican Republic",
    "El Salvador",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Nicaragua",
    "Panama",
    "Puerto Rico",
    "The Bahamas",
    "Trinidad and Tobago",
  ],
  AMERYKA_PD: [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Ecuador",
    "Falkland Islands",
    "Guyana",
    "Paraguay",
    "Peru",
    "Suriname",
    "Uruguay",
    "Venezuela",
  ],
  EUROPA: [
    "Albania",
    "Austria",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "England",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Kosovo",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Moldova",
    "Montenegro",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Republic of Serbia",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Ukraine",
  ],
  AFRYKA: [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Democratic Republic of the Congo",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea Bissau",
    "Ivory Coast",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Republic of the Congo",
    "Rwanda",
    "Senegal",
    "Sierra Leone",
    "Somalia",
    "Somaliland",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Swaziland",
    "Togo",
    "Tunisia",
    "Uganda",
    "United Republic of Tanzania",
    "Western Sahara",
    "Zambia",
    "Zimbabwe",
  ],
  BLISKI_WSCHOD: [
    "Bahrain",
    "Iran",
    "Iraq",
    "Israel",
    "Jordan",
    "Kuwait",
    "Lebanon",
    "Northern Cyprus",
    "Oman",
    "Qatar",
    "Saudi Arabia",
    "Syria",
    "Turkey",
    "United Arab Emirates",
    "West Bank",
    "Yemen",
  ],
  AZJA: [
    "Afghanistan",
    "Armenia",
    "Azerbaijan",
    "Bangladesh",
    "Bhutan",
    "Brunei",
    "Cambodia",
    "China",
    "East Timor",
    "Georgia",
    "India",
    "Indonesia",
    "Japan",
    "Kazakhstan",
    "Kyrgyzstan",
    "Laos",
    "Malaysia",
    "Mongolia",
    "Myanmar",
    "Nepal",
    "North Korea",
    "Pakistan",
    "Philippines",
    "Russia",
    "South Korea",
    "Sri Lanka",
    "Taiwan",
    "Tajikistan",
    "Thailand",
    "Turkmenistan",
    "Uzbekistan",
    "Vietnam",
  ],
  AUSTRALIA: ["Australia", "Fiji", "New Caledonia", "New Zealand", "Papua New Guinea", "Solomon Islands", "Vanuatu"],
};

const countryToRegion = new Map<string, ContinentKey>();
Object.entries(REGION_COUNTRIES).forEach(([region, countries]) => {
  countries.forEach((country) => {
    countryToRegion.set(country, region as ContinentKey);
  });
});

export function getRegionForCountry(countryName: string): ContinentKey | null {
  return countryToRegion.get(countryName) ?? null;
}
